<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.4">
  <POU Name="IsValid" Id="{d45c6f3b-0e7c-46e1-877e-65e9b45da4e8}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION IsValid : BOOL
VAR_INPUT
    status : TerminalStatus;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[IsValid := NOT (status.IOError OR status.WorkingCounterError);
]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>