<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.4">
  <POU Name="MAIN" Id="{bda779b6-34ba-4438-8015-baa0f5e2c171}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
    simRelay : SimRelay;
    simOven : SimOven;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[simRelay();
simOven();
]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>